export const SVJifErrorCode = {
  // Input / parse
  E_INPUT_EMPTY: 'SVJIF_E_INPUT_EMPTY',
  E_INPUT_INVALID_JSON: 'SVJIF_E_INPUT_INVALID_JSON',
  E_INPUT_INVALID_SDL: 'SVJIF_E_INPUT_INVALID_SDL',
  E_SCENE_MISSING: 'SVJIF_E_SCENE_MISSING',
  E_SCENE_MULTIPLE: 'SVJIF_E_SCENE_MULTIPLE',
  E_VERSION_UNSUPPORTED: 'SVJIF_E_VERSION_UNSUPPORTED',
  E_DIRECTIVE_UNKNOWN: 'SVJIF_E_DIRECTIVE_UNKNOWN',
  E_DIRECTIVE_ARG_UNKNOWN: 'SVJIF_E_DIRECTIVE_ARG_UNKNOWN',
  E_DIRECTIVE_ARG_INVALID_TYPE: 'SVJIF_E_DIRECTIVE_ARG_INVALID_TYPE',
  E_DIRECTIVE_ARG_MISSING: 'SVJIF_E_DIRECTIVE_ARG_MISSING',

  // Validation
  E_SCENE_DIMENSIONS_INVALID: 'SVJIF_E_SCENE_DIMENSIONS_INVALID',
  E_NODE_KIND_INVALID: 'SVJIF_E_NODE_KIND_INVALID',
  E_NODE_DUPLICATE_ID: 'SVJIF_E_NODE_DUPLICATE_ID',
  E_PARENT_NOT_FOUND: 'SVJIF_E_PARENT_NOT_FOUND',
  E_CYCLE_DETECTED: 'SVJIF_E_CYCLE_DETECTED',
  E_PROP_REQUIRED_MISSING: 'SVJIF_E_PROP_REQUIRED_MISSING',
  E_PROP_INVALID_VALUE: 'SVJIF_E_PROP_INVALID_VALUE',
  E_BIND_TARGET_NOT_FOUND: 'SVJIF_E_BIND_TARGET_NOT_FOUND',
  E_BIND_EXPR_INVALID: 'SVJIF_E_BIND_EXPR_INVALID',
  E_REF_TARGET_NOT_FOUND: 'SVJIF_E_REF_TARGET_NOT_FOUND',

  // Emit / runtime
  E_EMIT_TARGET_UNSUPPORTED: 'SVJIF_E_EMIT_TARGET_UNSUPPORTED',
  E_FEATURE_NOT_IMPLEMENTED: 'SVJIF_E_FEATURE_NOT_IMPLEMENTED',
  E_INTERNAL_INVARIANT: 'SVJIF_E_INTERNAL_INVARIANT',

  // Warnings
  W_UNUSED_FIELD: 'SVJIF_W_UNUSED_FIELD',
  W_STYLE_IGNORED_FOR_KIND: 'SVJIF_W_STYLE_IGNORED_FOR_KIND',
  W_PROP_OVERRIDDEN: 'SVJIF_W_PROP_OVERRIDDEN',
  W_BINARY_PACK_NOT_IMPLEMENTED: 'SVJIF_W_BINARY_PACK_NOT_IMPLEMENTED',
} as const;

export type SVJifErrorCodeValue = (typeof SVJifErrorCode)[keyof typeof SVJifErrorCode];
